### PR TITLE
Added Decompressors for LZKN SNES version variants 1 and 2

### PR DESCRIPTION
**Pull request by hansbonini**
Added related variants for SNES games.

Games covered by LZKN SNES 1:
```
[SNES] The Adventures of Batman & Robin
[SNES] Teenage Mutant Ninja Turtles IV - Turtles in Time
[SNES] Biker Mice From Mars 
[SNES] Contra III-The Alien Wars
[SNES] Animaniacs
[SNES] Batman Returns
```

Games covered by LZKN SNES 2:
```
[SNES] Soreyuke Ebisumaru Karakuri Meiro - Kieta Goemon no Nazo!!
```

### CODE REVIEW

**Comment by lab313ru** [comment]
Have you checked it? Does it work correctly?

**Comment by hansbonini** [comment]
> Have you checked it? Does it work correctly?

Only decompress functions works... i didn't make compress functions yet. Can you adjust code to compress too?

**Comment by lab313ru** [comment]
I can do that, but at this weekend.

**Comment by hansbonini** [comment]
> I can do that, but at this weekend.

Right, i'll research for more SNES variants. Apparently Castlevania games has another variant with alternate raw copy;

**Pull request closed without merging**
